### ISSUE TITLE
Stored procedure result set

### ISSUE THREAD

**Issue by vanackertom** [Fodsuk/EntityFrameworkExtras#10]
Hello,
I really like this approach to calling stored procedure with user defined table type parameters. I'm however to find a way to retrieve the resultset that is coming from the stored procedure. Can this be done using this approach? 
Greetings,
Tom

**Comment by Fodsuk** [comment]
Hey Tom,

To get the results back from your stored procedure, you would use the ExecuteStoredProcedure with the generic return type. 

For example

IEnumerable<Pet> pets=  tomsDbContext.Database.ExecuteStoredProcedure<Pet>(new GetAllPetsStoredProcedure());

so the Pet class would be your POCO object that would match what your Stored Procedure returns and the GetAllPetsStoredProcedure object would be a representative of your Stored Procedure).

**Comment by vanackertom** [comment]
So easy ... I'm ashamed to have missed that .. thank you.

**Comment by pjanssen007** [comment]
I tried this solution but the return type from ExecuteStoredProcedure is void.  I don't get a result set from my stored proc.

**Comment by pjanssen007** [comment]
Nevermind.  I figured out I need to specify the return poco type in the call to ExecuteStoreProcedure<>.
