### ISSUE TITLE
Assemblies are not signed

### ISSUE THREAD

**Issue by RyanRedrum** [Fodsuk/EntityFrameworkExtras#12]
Hello,

I am trying to use the EF6 package with a solution that requires all of our assemblies to be signed.  I am unable to build my solution with this package referenced because the assembly it adds is not signed.  Is it possible for that to be added?

Thanks,
Ryan

**Comment by Fodsuk** [comment]
Hey Ryan,

Unfortunately i don't have any future plans to sign the assemblies.

Kind Regards,

Mike
