### ISSUE TITLE
Avoid using sp_ as a prefix for stored procedures in your examples.

### ISSUE THREAD

**Issue by sonnemaf** [Fodsuk/EntityFrameworkExtras#14]
Avoid using sp_ as a prefix for stored procedures. Read 
https://msdn.microsoft.com/en-us/library/dd172115(v=vs.100).aspx
http://sqlperformance.com/2012/10/t-sql-queries/sp_prefix

**Comment by Fodsuk** [comment]
i've updated the readme with out 'sp_' in the example.
